//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redbus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmBooking
    {
        public int BookingId { get; set; }
        public int BusId { get; set; }
        public int SeatNumber { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public int Age { get; set; }
        public decimal Fare { get; set; }
        public Nullable<System.DateTime> BookingTime { get; set; }
        public string boardingpoint { get; set; }
        public string pickuppoint { get; set; }
    }
}
