//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace redbus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public int SeatId { get; set; }
        public Nullable<int> BusId { get; set; }
        public string SeatNumber { get; set; }
        public Nullable<bool> IsBooked { get; set; }
    
        public virtual Bus Bus { get; set; }
    }
}
